  #version: '3.9'
  services:
    db:
      #image: mahmud740/dbpost:latest
      image: postgres:15
      container_name: Database
      environment:
        POSTGRES_DB: book-store
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: maki
      ports:
        - "5432:5432"
      restart: always
      networks:
        - app-network
      volumes:
        - pgdata:/var/lib/postgresql/data
#        - pgdata:/var/run/postgresql/.s.PGSQL.5432

    app:
      container_name: SpringApp
#      image: mahmud740/springapplication:latest
      image: mahmud740/spapp:2.0
      build: .
      ports:
        - "8080:8080"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book-store
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: maki
        #SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
        #SPRING_JPA_SHOW_SQL: true
        SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
        SPRING_JPA_HIBERNATE_DDL_AUTO: update

      networks:
        - app-network
      depends_on:
        - db
  volumes:
    pgdata: #{ }

  networks:
    app-network:
      driver: bridge
